[doctest] doctest version is "1.2.5"
[doctest] run with "--help" for options
===============================================================================
coverage_maxout.cpp(26)
TEST CASE:  doctest internals

TEST CASE FAILED!
crashed:
  

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |      3 skipped
[doctest] assertions:      0 |      0 passed |      0 failed |
[doctest] Status: FAILURE!
coverage_maxout.cpp(33) PASSED!
  CHECK( detail::SubcaseSignature("", "a.cpp", 0) < detail::SubcaseSignature("", "b.cpp", 0) )
with expansion:
  CHECK( {?} <  {?} )

coverage_maxout.cpp(35) PASSED!
  CHECK( String("a.cpp") < String("b.cpp") )
with expansion:
  CHECK( a.cpp <  b.cpp )

coverage_maxout.cpp(41) PASSED!
  CHECK( a.size() == const_str.size() )
with expansion:
  CHECK( 9 == 9 )

coverage_maxout.cpp(42) ERROR!
  CHECK( a.compare(const_str, true) != 0 )
with expansion:
  CHECK( 0 != 0 )
with context:
  should fail

coverage_maxout.cpp(43) ERROR!
  CHECK( a.compare("omgomgomg", false) != 0 )
with expansion:
  CHECK( 0 != 0 )
with context:
  should fail

coverage_maxout.cpp(90) ERROR!
  CHECK( len_is_zero )
with expansion:
  CHECK( false )
with context:
  should fail

0.000641 s: doctest internals
===============================================================================
coverage_maxout.cpp(94)
TEST SUITE: exception related
TEST CASE:  will end from a std::string exception

TEST CASE FAILED!
threw exception:
  std::string!

0.000718 s: will end from a std::string exception
===============================================================================
coverage_maxout.cpp(98)
TEST SUITE: exception related
TEST CASE:  will end from a const char* exception

TEST CASE FAILED!
threw exception:
  const char*!

0.000066 s: will end from a const char* exception
===============================================================================
coverage_maxout.cpp(102)
TEST SUITE: exception related
TEST CASE:  will end from an unknown exception

TEST CASE FAILED!
threw exception:
  unknown exception

0.000081 s: will end from an unknown exception
===============================================================================
[doctest] test cases:      4 |     -1 passed |      5 failed |      0 skipped
[doctest] assertions:      6 |      3 passed |      3 failed |
[doctest] Status: FAILURE!
